services:
  db:
    image: postgres:15
    container_name: adproxy_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: adproxy_redis
    restart: unless-stopped

  pyload:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: adproxy_pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - "8000:8000"
      - "9666:9666"  # Optional click'n'load port
    volumes:
      - ./config/pyload:/config
      - /srv/storage:/downloads
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: adproxy_migrations
    command: ["alembic", "upgrade", "head"]
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - db
    restart: "no"
    volumes:
      - /srv/storage:/srv/storage

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: adproxy_api
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
      pyload:
        condition: service_started
    volumes:
      - /srv/storage:/srv/storage
    ports:
      - "9731:8080"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: adproxy_worker
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - api
      - pyload
    volumes:
      - /srv/storage:/srv/storage
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: adproxy_frontend
    ports:
      - "${FRONTEND_PORT:-5000}:5000"
    #environment:
   #   - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - /srv/storage:/srv/storage
    restart: unless-stopped


volumes:
  db_data:
